---
title: "bootstrapping"
date: "2023-11-16"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## Bootstrapping in SLR

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const |> 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)
```

Fit linear model

```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 

sim_df |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```

# draw and analyse 

function

```{r}
boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}
```

check

```{r}
boot_sample(sim_df_nonconst) |> 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm")
```

# Draw a lot of samples and analyze them

```{r}
boot_straps = 
  tibble(strap_number = 1:1000) |> 
  mutate(
    strap_sample = map(strap_number, \(i) boot_sample(df = sim_df_nonconst))
  )

boot_straps

boot_straps |> 
  pull(strap_sample) |> 
  nth(2) |> 
  arrange(x)
```

`lm` fit

```{r}
bootstrap_results = 
  boot_straps |> 
  mutate(
    models = map(strap_sample, \(df) lm(y ~ x, data = df)),
    results = map(models, broom::tidy)
    ) |> 
  select(strap_number, results) |> 
  unnest(results) 
```

summarize these results -- get a bootstrap SE

```{r}
bootstrap_results |> 
  group_by(term) |> 
  summarize(
    se = sd(estimate)
    ) |> 
  knitr::kable(digits = 3)
```

distribution

```{r}
bootstrap_results |>
  filter(term == "x") |>
  nth(2) |>
  arrange(x)
```

construct a CI

```{r}
bootstrap_results |> 
  group_by(term) |> 
  summarize(
    ci_lower = quantile(estimate, 0.025), 
    ci_upper = quantile(estimate, 0.975)
    ) 
```


